trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_IN_AUTOMATION: 'true'
  TERRAFORM_VERSION: '1.5.0'

steps:
# Install Terraform (from the marketplace extension you already installed)
- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '$(TERRAFORM_VERSION)'

# Login to Azure using the service connection
- task: AzureCLI@2
  displayName: 'Azure CLI login via service connection'
  inputs:
    azureSubscription: 'akhil'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged in successfully"
      az account show --query "{name:name, id:id}" -o table

# Run Terraform commands (using the Azure CLI auth context)
- script: |
    terraform init -input=false
    terraform plan -out=tfplan -input=false
    terraform apply -auto-approve tfplan
  displayName: 'Terraform init/plan/apply'
